Currencies.Web/Models/Currencies/ConversionResultViewModel.cs
namespace Currencies.Web.Models.Currencies
{
    public class ConversionResultViewModel
    {
        public decimal Result { get; set; }
    }
}

Currencies.Web/Models/Currencies/CurrencyViewModel.cs
using System;

namespace Currencies.Web.Models.Currencies
{
    public class CurrencyViewModel
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public decimal Rate { get; set; }
        public DateTime Date { get; set; }
    }
}

Currencies.Web/Models/ErrorViewModel.cs
using System;

namespace Currencies.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Currencies.Web/Controllers/CurrenciesController.cs
using AutoMapper;
using Currencies.Business.Services;
using Currencies.Web.Models.Currencies;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Currencies.Web.Controllers
{
    public class CurrenciesController : Controller
    {
        private readonly ICurrenciesService _currenciesService;
        private readonly IMapper _mapper;

        public CurrenciesController(ICurrenciesService currenciesService,
                                    IMapper mapper)
        {
            _currenciesService = currenciesService;
            _mapper = mapper;
        }
        
        public async Task<IActionResult> Currencies()
        {
            var currencies = await _currenciesService.GetCurrencies();
            var currencyViewModel = _mapper.Map<IEnumerable<CurrencyViewModel>>(currencies);
            
            return View(currencyViewModel);
        }
    }
}

Currencies.Web/Controllers/HomeController.cs
using AutoMapper;
using Currencies.Business.Services;
using Currencies.Web.Models.Currencies;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Currencies.Web.Controllers
{
    public class HomeController : Controller
    {

        private readonly ICurrenciesService _currenciesService;
        private readonly IMapper _mapper;

        public HomeController(ICurrenciesService currenciesService,
                                    IMapper mapper)
        {
            _currenciesService = currenciesService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Converter()
        {
            var currenciesResponse = await _currenciesService.GetLastCurrencies();
            var currencyViewModel = _mapper.Map<IEnumerable<CurrencyViewModel>>(currenciesResponse);

            return View(currencyViewModel);
        }

        public async Task<IActionResult> InsertCurrencies()
        {
            await _currenciesService.InsertCurrencies();
            return View("ImportSuccess");
        }

        public IActionResult Convert(decimal fromAmount, decimal fromRate, decimal toRate)
        {
            var model = new ConversionResultViewModel();
            model.Result = _currenciesService.CurrenciesConverter(fromAmount, fromRate, toRate);
                       
            return View("Result", model);
        }
    }
}

Currencies.Web/Views/Currencies/Currencies.cshtml
@model IEnumerable<Currencies.Web.Models.Currencies.CurrencyViewModel>
<h1>@ViewData["Title"]</h1>

<div id="table">
    <table class="table table-striped" id="currencies">
        <thead>
            <tr>
                <th style="width: 30%">Date</th>
                <th style="width: 30%">Currency</th>
                <th style="width: 40%">Rate</th>
            </tr>
        </thead>
        <tbody>
           @foreach (var item in Model)
            {
            <tr>
                <td class="">@item.Date.ToString("yyyy-MM-dd")</td>
                <td class=""><spam>@item.Value</spam></td>
                <td class=""><spam>@item.Rate</spam></td>
            </tr>
            }
        </tbody>
    </table>
</div>

Currencies.Web/Views/Home/Converter.cshtml
@model IEnumerable<Currencies.Web.Models.Currencies.CurrencyViewModel>
@Html.ValidationSummary(false, "", new { @class = "text-danger" })


<a asp-area="" asp-controller="Home" asp-action="InsertCurrencies" data-target="#modal-action-customer"
   class="btn btn-info">
    <i class="glyphicon glyphicon-trash"> Insert new currencies</i>
</a>
<div class="text-center">
    <h1 class="display-4">Welcome to currencies converter</h1>
</div>

@using (Html.BeginForm("Convert", "Home"))
 {
     <div class="row">
         <div class="col-lg-12 col-md-12 col-12">
             <div class="row justify-content-center">
                 <label class="font-weight-bold">Please insert amount</label>
             </div>
             <div class="row justify-content-center">
                 <input class="form-control" style="width:100px" name="fromAmount" />
             </div>
         </div>
         <div class="col-lg-6 col-md-6 col-6">
             <div class="row justify-content-center">
                 <div>
                     <label class="font-weight-bold">Currency From : </label>
                     <select class="custom-select" name="fromRate"
                             style="width:150px;">
                         <option value="1">EUR</option>
                         @foreach (var item in Model)
                         {
                             <option value="@item.Rate">@item.Value</option>
                         }
                     </select>
                 </div>
             </div>
         </div>
         <div class="col-lg-6 col-md-6 col-6">
             <div class="row justify-content-center">
                 <div>
                     <label class="font-weight-bold">Currency To : </label>
                     <select class="custom-select justify-content-center" name="toRate"
                             style="width:150px;">
                         <option value="1">EUR</option>
                         @foreach (var item in Model)
                         {
                             <option value="@item.Rate"> @item.Value</option>
                         }
                     </select>
     
                 </div>
             </div>
         </div>
         <div class="col-lg-12 col-md-12 col-12">
             <div class="row justify-content-center">
                 <input type="submit" class="btn btn-secondary" value="Convert" />
             </div>
         </div>
     </div>
 }

Currencies.Web/Views/Home/ImportSuccess.cshtml
<h1>Import success</h1>

Currencies.Web/Views/Home/Result.cshtml
@model Currencies.Web.Models.Currencies.ConversionResultViewModel
<h1>Result</h1>
<p>@Model.Result</p>

Currencies.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Currencies.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Converter">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Currencies" asp-action="Currencies">Currencies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Currencies.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>